org.gradle.jvmargs=-Xmx1200m -XX:MaxMetaspaceSize=384m -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.workers.max=1
kotlin.code.style=official
kotlin.incremental=true
kotlin.compiler.execution.strategy=in-process
android.useAndroidX=true
android.nonTransitiveRClass=true
android.nonFinalResIds=true
android.suppressUnsupportedCompileSdk=36
systemProp.http.proxyHost=egress-proxy.sandbox.internal
systemProp.http.proxyPort=3128
systemProp.http.nonProxyHosts=localhost|127.0.0.1|*.svc.cluster.local
systemProp.https.proxyHost=egress-proxy.sandbox.internal
systemProp.https.proxyPort=3128
systemProp.https.nonProxyHosts=localhost|127.0.0.1|*.svc.cluster.local
